#!/bin/bash

source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2

set -e

pushd "$(dirname "$0")" >/dev/null


if [ ! "$1" ]; then
	echo "usage: $0 HOST"
	echo "deploys setup source code to remote HOST."
	exit 1
fi

HOST="$1"
REPO="$(basename "$(pwd)")"

run "tar zcf - --exclude .git '../$REPO' | ssh $HOST 'tar xzf -'"
run "ssh $HOST 'set -e; pushd '$REPO'; yes | ./install; popd; rm -rf setup'"
show "deployment complete!"
