#!/bin/bash

source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2

set -e

if [ ! "$1" ]; then
	echo "usage: $0 HOST"
	echo "deploys setup source code to remote HOST."
	exit 1
fi

HOST="$1"
REPO="$(basename "$(pwd)")"

run "tar zcvf - \"../$REPO\" | ssh $HOST \"tar xvzf -\""
run "ssh $HOST \"cd '$REPO'; yes | ./install\""
show "deployment complete!"
