#!/bin/bash

# Installs bin and env from this repository.

rsync -apl env/dot_shell_control "$HOME/.shell_control"
source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2

set -e

( run "pushd env"; run "./install" )
( run "pushd bin"; run "./install" )

show "Install complete!"
