#!/bin/bash

if [[ ! -f /Library/Fonts/Inconsolata.otf ]]; then
	echo "Installing Inconsolata font"
	pushd /tmp
	curl -vO http://levien.com/type/myfonts/Inconsolata.otf
	mv -vf Inconsolata.otf /Library/Fonts
	popd
fi

echo "Enable repeat on keydown"
defaults write -g ApplePressAndHoldEnabled -bool false

echo "Use current directory as default search scope in Finder"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

echo "Show Path bar in Finder"
defaults write com.apple.finder ShowPathbar -bool true

echo "Show Status bar in Finder"
defaults write com.apple.finder ShowStatusBar -bool true

echo "Show indicator lights for open applications in the Dock"
defaults write com.apple.dock show-process-indicators -bool true

echo "Enable AirDrop over Ethernet and on unsupported Macs running Lion"
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

echo "Set a blazingly fast keyboard repeat rate"
defaults write NSGlobalDomain KeyRepeat -int 0.02

echo "Set a shorter Delay until key repeat"
defaults write NSGlobalDomain InitialKeyRepeat -int 12

echo "Disable disk image verification"
defaults write com.apple.frameworks.diskimages skip-verify -bool true &&
	defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true &&
	defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

echo "Disable Safari’s thumbnail cache for History and Top Sites"
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

echo "Enable Safari’s debug menu"
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

echo "Disable the Ping sidebar in iTunes"
defaults write com.apple.iTunes disablePingSidebar -bool true

echo "Add a context menu item for showing the Web Inspector in web views"
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

echo "Show the ~/Library folder"
chflags nohidden ~/Library

echo "Disable ping dropdowns"
defaults write com.apple.iTunes hide-ping-dropdown true

echo "Disable app_to_run for XQuartz X11"
defaults write org.macosforge.xquartz.X11 app_to_run /usr/bin/true

echo "Configuring git"
git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
git config --global alias.s "status -uno"

echo "Disable two finger gesture navigation on Chrome"
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE

HOST="$(uname -n)"
read -p "Set hostname... [$HOST]: "
[[ -z "$REPLY" ]] && REPLY="$HOST"
sudo scutil --set HostName $REPLY
