#!/bin/bash

# Updates the bin and env directories with whatever new changes are found in the current environment

source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2

set -e

pushd "$(dirname "$0")" >/dev/null


if [[ -n "$(git status -s)" ]]; then
	abort "cowardly refusing to overwrite existing changes"
fi

(
	run "pushd bin >/dev/null"
	run "./update_bin"

	show "Generating README.md..."
	USAGEBEGIN="$(./usages -t 2>&1 | head -n 1)"
	READMECONTENT="$(sed -n "/$USAGEBEGIN/q;p" ../README.md)"
	cat >../README.md <<EOF
$READMECONTENT

$(./usages -t)
EOF
)

(
	run "pushd env >/dev/null"
	run "./update_env"
)

show "Generating LICENSE..."
cat >LICENSE <<EOF
Copyright (c) $(date "+%Y"), amy@lexicalunit.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Inconsolata font Created by Raph Levien using his own tools and FontForge.
Copyright 2006 Raph Levien. Released under the SIL Open Font License.
EOF

show "Adding license to README.md..."
cat >>README.md <<EOF

# License
$(cat LICENSE)
EOF
