#!/bin/bash

# Updates the bin and env directories with whatever new changes are found in the current environment

source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2

set -e

if [[ -n "$(git status -s)" ]]; then
	abort "cowardly refusing to overwrite existing changes"
fi

(
	run "pushd bin >/dev/null"
	run "./update_bin"
	run "perl -ni -e 'print unless /^\|.*/' ../README.md"
	run "./usages -t >>../README.md"
)

(
	run "pushd env >/dev/null"
	run "./update_env"
)
