#!/bin/bash

# updates env with whatever new changes are found in the current environment

source "$HOME/.shell_control" || echo "$(tput bold)error: ~/.shell_control not installed!$(tput sgr0)" >&2

# profile
run "rsync -apl '$HOME/.profile' ./dot_profile"
for I in "$HOME/".profile_*; do
	if [[ ! -f ignore ]] || ! grep -q "$(basename "$I")" ignore; then
    	run "rsync -apl '$I' './$(basename "$I" | sed 's/^./dot_/')'"
	fi
done

# bash
[[ -f "$HOME/.bash_profile" ]] && run "rsync -apl '$HOME/.bash_profile' ./dot_bash_profile"
[[ -f "$HOME/.bashrc" ]] && run "rsync -apl '$HOME/.bashrc' ./dot_bashrc"

# zsh
[[ -f "$HOME/.zshrc" ]] && run "rsync -apl '$HOME/.zshrc' ./dot_zshrc"
[[ -f "$HOME/.zprofile" ]] && run "rsync -apl '$HOME/.zprofile' ./dot_zprofile"

# tools
[[ -f "$HOME/.dircolors" ]] && run "rsync -apl '$HOME/.dircolors' ./dot_dircolors"
[[ -f "$HOME/.inputrc" ]] && run "rsync -apl '$HOME/.inputrc' ./dot_inputrc"
[[ -f "$HOME/.vimrc" ]] && run "rsync -apl '$HOME/.vimrc' ./dot_vimrc"
[[ -f "$HOME/.hgignore" ]] && run "rsync -apl '$HOME/.hgignore' ./dot_hgignore"
[[ -f "$HOME/.hgrc" ]] && run "rsync -apl '$HOME/.hgrc' ./dot_hgrc"
[[ -f "$HOME/.gitconfig" ]] && run "rsync -apl '$HOME/.gitconfig' ./dot_gitconfig"
[[ -f "$HOME/.pythonrc" ]] && run "rsync -apl '$HOME/.pythonrc'.py ./dot_pythonrc.py"
[[ -f "$HOME/.toprc" ]] && run "rsync -apl '$HOME/.toprc' ./dot_toprc"
[[ -d "$HOME/.complete/" ]] && run "rsync -apl '$HOME/.complete/' ./dot_complete"

# atom
backup_atom()
{
	[[ -f "$HOME/.atom/$1" ]] && run "rsync -apl '$HOME/.atom/$1' ./atom.$1"
}
backup_atom "config.cson"
backup_atom "keymap.cson"
backup_atom "init.coffee"
backup_atom "styles.less"

# sublime text
backup_st()
{
	if [[ -e "$1/$2" ]]; then
		run "rsync -apl '$1/$2' '$2'"
	fi
}
backup_st "$HOME/Library/Application Support/Sublime Text 3/Packages/User" "Preferences.sublime-settings"
backup_st "$HOME/Library/Application Support/Sublime Text 3/Packages/User" "SublimePython.sublime-settings"
