#!/bin/bash

# updates env with whatever new changes are found in the current environment

function backup()
{
	rsync -avl "$1/$2" "$2"
}

# profile
rsync -avl ~/.profile ./dot_profile
for I in ~/.profile_*; do
    echo "considering: $I"
    if [[ -z "$(grep "$(basename "$I")" ignore)" ]]; then
        echo "adding: $I"
        rsync -avl "$I" "./$(basename "$I" | sed 's/^./dot_/')"
    fi
done

# bash
rsync -avl ~/.bash_profile ./dot_bash_profile
rsync -avl ~/.bashrc ./dot_bashrc

# zsh
rsync -avl ~/.zshrc ./dot_zshrc

# tools
rsync -avl ~/.dircolors ./dot_dircolors
rsync -avl ~/.inputrc ./dot_inputrc
rsync -avl ~/.vimrc ./dot_vimrc
rsync -avl ~/.hgignore ./dot_hgignore
rsync -avl ~/.hgrc ./dot_hgrc
rsync -avl ~/.gitconfig ./dot_gitconfig
rsync -avl ~/.pythonrc.py ./dot_pythonrc.py
rsync -avl ~/.toprc ./dot_toprc
rsync -avl ~/.complete/ ./dot_complete

backup ~/"Library/Application Support/Sublime Text 3/Packages/User" "Preferences.sublime-settings"
backup ~/"Library/Application Support/Sublime Text 3/Packages/User" "SublimePython.sublime-settings"
